name: "CI"

on:
  push:
    branches:
      - "main"

env:
  SOLUTION_PATH: src/GameLib.sln
  PACKAGE_OUTPUT_DIR: ${{ github.workspace }}\output
  NUGET_SOURCE_URL: "https://api.nuget.org/v3/index.json"

jobs:
  build:
    name: "build"
    runs-on: "windows-latest"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Install dotnet"
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0.x"

      - name: "Restore packages"
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: "Build project"
        run: dotnet build ${{ env.SOLUTION_PATH }} --no-restore --configuration Release

      - name: "Pack project"
        run: dotnet pack ${{ env.SOLUTION_PATH }} --no-restore --configuration Release --include-symbols --output ${{ env.PACKAGE_OUTPUT_DIR }}

      - name: "Push package"
        run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIR }}\*.nupkg --api-key ${{ secrets.NUGET_AUTH_TOKEN }} --source ${{ env.NUGET_SOURCE_URL }}
